services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # tcp
      - "15672:15672" # interface 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: